# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("remote.proto", :syntax => :proto3) do
    add_message "prometheus.WriteRequest" do
      repeated :timeseries, :message, 1, "prometheus.TimeSeries"
    end
    add_message "prometheus.ReadRequest" do
      repeated :queries, :message, 1, "prometheus.Query"
    end
    add_message "prometheus.ReadResponse" do
      repeated :results, :message, 1, "prometheus.QueryResult"
    end
    add_message "prometheus.Query" do
      optional :start_timestamp_ms, :int64, 1
      optional :end_timestamp_ms, :int64, 2
      repeated :matchers, :message, 3, "prometheus.LabelMatcher"
      optional :hints, :message, 4, "prometheus.ReadHints"
    end
    add_message "prometheus.QueryResult" do
      repeated :timeseries, :message, 1, "prometheus.TimeSeries"
    end
  end
end

module Prometheus
  WriteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.WriteRequest").msgclass
  ReadRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ReadRequest").msgclass
  ReadResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.ReadResponse").msgclass
  Query = Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.Query").msgclass
  QueryResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("prometheus.QueryResult").msgclass
end
