sumologic:
  accessId: suze3TMQURXG6X
  accessKey: eVgcGSJsf6JfdxnYboenxe7NPQgJ8KUxR89L67bjYb1SiEyZjHn8pAu8D0yFgf5P
  clusterName: events-sdhruv-testing
  collectorName: events-sdhruv-testing-k8sobject
  endpoint: https://long-api.sumologic.net/api/v1/
# http://sumo4-sumologic-metadata-logs.sumologic4.svc.cluster.local.:4322/v1/logs
#
#  curl -X POST \
#  http://sumo4-sumologic-metadata-logs.sumologic4.svc.cluster.local.:4322/v1/logs \
#-H "Content-Type: application/json" \
#  -d '{
#"resourceLogs": [
#  {
#    "resource": {
#      "attributes": [
#        { "key": "service.name", "value": { "stringValue": "test-service" } }
#      ]
#    },
#    "scopeLogs": [
#      {
#        "scope": {
#          "name": "curl-test"
#        },
#        "logRecords": [
#          {
#            "timeUnixNano": "1710000000000000000",
#            "severityNumber": 9,
#            "severityText": "INFO",
#            "body": {
#              "stringValue": "log generated for custom pipeline using curl"
#            }
#          }
#        ]
#      }
#    ]
#  }
#]
#}'
