FROM fluent/fluentd:v1.4.0-debian-onbuild-1.0

# Use root account to use apt
USER root

COPY gems/fluent-plugin*.gem ./

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps

RUN sudo apt-get install -y --no-install-recommends python-tk python-setuptools ipython

RUN sudo gem install google-protobuf

# For some reason following gem fail to install ??
RUN sudo gem install snappy

RUN sudo gem install fluent-plugin-sumologic_output \
 && sudo gem install fluent-plugin-carbon-v2 \
 && sudo gem install fluent-plugin-datapoint \
 && sudo gem install fluent-plugin-rewrite-tag-filter \
 && sudo gem install fluent-plugin-prometheus-format \
 && sudo gem install fluent-plugin-probuf

RUN sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

USER fluent
