source 'https://rubygems.org'

gem 'kubeclient', git: 'https://github.com/abonas/kubeclient/', ref: '3267dc3fd02c49e3b19f1210ff7cb84c3b2a4478'

gem 'codeclimate-test-reporter', '<1.0.0', :group => :test, :require => nil
gem 'rubocop', require: false

# Specify your gem's dependencies in fluent-plugin-add.gemspec
gemspec
