{
 "title": "K8s perf dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus in-out rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_in_total[5m]) - ignoring(queue) group_right(service) (rate(prometheus_remote_storage_dropped_samples_total[5m]) + rate(prometheus_remote_storage_succeeded_samples_total[5m]))"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_in_total[5m]) - ignoring(url,remote_name) group_right(service) (rate(prometheus_remote_storage_dropped_samples_total[5m]) + rate(prometheus_remote_storage_succeeded_samples_total[5m]))"
      }
     ]
    },
    {
     "title": "Fluentd-metrics containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{pod=~\".*fluentd-metrics-.*\"})"
      }
     ]
    },
    {
     "title": "metrics by fluentd ip",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(receiver_mock_metrics_ip_count[1m])) by (ip_address) * 60"
      }
     ]
    },
    {
     "title": "avalanche containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{container=\"avalanche\",pod=~\".*avalanche.*\"})"
      }
     ]
    },
    {
     "title": "Prometheus Remote Storage Drop/Failure rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_failed_samples_total[1m])"
      }
     ]
    },
    {
     "title": "Prometheus Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[1m]))"
      }
     ]
    },
    {
     "title": "Metrics Fluentd Combined CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"collection-sumologic-fluentd-metrics.*\",container=\"fluentd\"}[1m]))"
      }
     ]
    },
    {
     "title": "Metrics Fluentd Combined Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_memory_working_set_bytes{pod=~\"collection-sumologic-fluentd-metrics.*\"}[1m])) by (pod)"
      }
     ]
    },
    {
     "title": "Metrics Fluentd Queue Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length{pod=~'collection-sumologic-fluentd-metrics.*'}[1m])"
      }
     ]
    },
    {
     "title": "Metrics Fluentd CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"fluentd\", pod=~\"collection-sumologic-fluentd-metrics.*\"}[1m]) > 0)",
       "legendFormat": "avg"
      },
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"fluentd\", pod=~\"collection-sumologic-fluentd-metrics.*\"}[1m])"
      }
     ]
    },
    {
     "title": "Metrics Fluentd Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_memory_working_set_bytes{container=\"fluentd\", pod=~\"collection-sumologic-fluentd-metrics.*\"}[1m])/1024/1024"
      }
     ]
    },
    {
     "title": "Prometheus rate of Success",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_succeeded_samples_total[1m])"
      }
     ]
    },
    {
     "title": "Logs ingestion rate (MB/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(receiver_mock_logs_bytes_count[1m]))/1024/1024",
       "legendFormat": "Received traffic"
      },
      {
       "expr": "sum(kube_pod_container_status_ready{pod=~\".*util.*\"})/8",
       "legendFormat": "Generated traffic"
      }
     ]
    },
    {
     "title": "Prometheus Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "GiB" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"prometheus-collection-kube-prometheus-prometheus.*$\",container=~\".+\"}/1024/1024/1024) by (pod)"
      }
     ]
    },
    {
     "title": "Prometheus Rate of Retry",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_retried_samples_total[1m])"
      }
     ]
    },
    {
     "title": "API server request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fluentbit in-out rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_bytes_total[1m])/1024/1024) - sum(rate(fluentbit_output_proc_bytes_total[1m])/1024/1024)"
      }
     ]
    },
    {
     "title": "fluent-bit in rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_bytes_total[1m])/1024/1024)"
      }
     ]
    },
    {
     "title": "Fluent-bit out rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_bytes_total[1m])/1024/1024)"
      }
     ]
    },
    {
     "title": "Fluent-bit retries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_retries_total[1m]))"
      }
     ]
    },
    {
     "title": "Logs Fluentd Combined Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_memory_working_set_bytes{container=\"fluentd\", pod=~'collection-sumologic-fluentd-logs.*'}[1m])/1024/1024) by (pod)"
      }
     ]
    },
    {
     "title": "Fluentd-logs containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{pod=~\".*-logs-.*\"})"
      }
     ]
    },
    {
     "title": "API server request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[1m]))"
      }
     ]
    },
    {
     "title": "log utils target traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{pod=~\"util-.*\"})/8"
      }
     ]
    },
    {
     "title": "Logs Fluentd Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_memory_working_set_bytes{container=\"fluentd\", pod=~'collection-sumologic-fluentd-logs.*'}[1m])/1024/1024"
      }
     ]
    },
    {
     "title": "Fluent-bit CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"fluent-bit\"}[1m])"
      }
     ]
    },
    {
     "title": "Logs Fluentd CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"fluentd\", pod=~'collection-sumologic-fluentd-logs.*'}[1m])"
      }
     ]
    },
    {
     "title": "Receiver CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"receiver-mock\"}[1m])"
      }
     ]
    },
    {
     "title": "Logs Fluentd Combined CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"fluentd\", pod=~'collection-sumologic-fluentd-logs.*'}[1m])) by (pod)"
      }
     ]
    },
    {
     "title": "Logs Fluentd Queue Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length{pod=~'collection-sumologic-fluentd-logs.*'}[1m])"
      }
     ]
    },
    {
     "title": "API Server Request Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_count[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_free_bytes)/(node_filesystem_size_bytes) * 100"
      }
     ]
    },
    {
     "title": "Disk I/O Read Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m])/1024/1024"
      }
     ]
    },
    {
     "title": "Disk I/O Write Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[1m])/1024/1024"
      }
     ]
    },
    {
     "title": "Disk Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node:node_disk_utilisation:avg_irate"
      }
     ]
    },
    {
     "title": "Network Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total[1m])"
      }
     ]
    }
   ]
  }
 ]
}