{
 "title": "Receiver Summary",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Metrics Ingestion Rate (DPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(receiver_mock_metrics_count[1m]))*60",
     "legendFormat": "Received DPM"
    }
   ]
  },
  {
   "title": "Logs ingestion rate (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(receiver_mock_logs_bytes_count[1m]))/1024/1024",
     "legendFormat": "Received traffic"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{pod=~\".*util.*\"})/8",
     "legendFormat": "Generated traffic"
    }
   ]
  },
  {
   "title": "Receiver CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"receiver-mock\"}[1m])"
    }
   ]
  },
  {
   "title": "Receiver Memory MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"receiver-mock\"}[1m])/1024/1024"
    }
   ]
  },
  {
   "title": "Receiver mock containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{pod=~\"receiver-mock-.*\"})"
    }
   ]
  }
 ]
}