// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaAutoInstrumentation) DeepCopyInto(out *JavaAutoInstrumentation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaAutoInstrumentation.
func (in *JavaAutoInstrumentation) DeepCopy() *JavaAutoInstrumentation {
	if in == nil {
		return nil
	}
	out := new(JavaAutoInstrumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaAutoInstrumentation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaAutoInstrumentationList) DeepCopyInto(out *JavaAutoInstrumentationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JavaAutoInstrumentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaAutoInstrumentationList.
func (in *JavaAutoInstrumentationList) DeepCopy() *JavaAutoInstrumentationList {
	if in == nil {
		return nil
	}
	out := new(JavaAutoInstrumentationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaAutoInstrumentationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaAutoInstrumentationSpec) DeepCopyInto(out *JavaAutoInstrumentationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaAutoInstrumentationSpec.
func (in *JavaAutoInstrumentationSpec) DeepCopy() *JavaAutoInstrumentationSpec {
	if in == nil {
		return nil
	}
	out := new(JavaAutoInstrumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaAutoInstrumentationStatus) DeepCopyInto(out *JavaAutoInstrumentationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaAutoInstrumentationStatus.
func (in *JavaAutoInstrumentationStatus) DeepCopy() *JavaAutoInstrumentationStatus {
	if in == nil {
		return nil
	}
	out := new(JavaAutoInstrumentationStatus)
	in.DeepCopyInto(out)
	return out
}
