#!/usr/bin/env bash

read -d '' usage << EOF
This image provides a set of tools for Kubernetes Collection. You can use following commands:

 * K8S Check for verifying the environment:

 kubectl run tools --generator=run-pod/v1 -it --rm --restart=Never --image sumologic/kubernetes-tools -- check

 * K8S template generator

  docker run --rm kubernetes-tools \
    template \
    --namespace '<NAMESPACE>' \
    --name-template 'collection' \
    --set sumologic.accessId='<ACCESS_KEY>' \
    --set sumologic.accessKey='<ACCESS_ID>' \
    --set sumologic.collectorName='<COLLECTOR_NAME>' \
    --set sumologic.clusterName='<CLUSTER_NAME>' \
    | tee sumologic.yaml
  
  or

  kubectl run tools --generator=run-pod/v1 -it --rm --restart=Never --image sumologic/kubernetes-tools -- \
    template \
    --namespace '<NAMESPACE>' \
    --name-template 'collection' \
    --set sumologic.accessId='<ACCESS_KEY>' \
    --set sumologic.accessKey='<ACCESS_ID>' \
    --set sumologic.collectorName='<COLLECTOR_NAME>' \
    --set sumologic.clusterName='<CLUSTER_NAME>' \
    | tee sumologic.yaml

 * Interactive mode:

 kubectl run tools --generator=run-pod/v1 -it --rm --restart=Never --image sumologic/kubernetes-tools -- /bin/bash -l
EOF

echo "$usage"